/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Form } from "./components/app-focus3/focus";
export namespace Components {
    interface AppFocus1 {
    }
    interface AppFocus2 {
    }
    interface AppFocus3 {
    }
    interface AppHome {
    }
    interface AppInput {
        "disabled": boolean;
        "form": Form;
        "tabIndex": number;
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppFocus1Element extends Components.AppFocus1, HTMLStencilElement {
    }
    var HTMLAppFocus1Element: {
        prototype: HTMLAppFocus1Element;
        new (): HTMLAppFocus1Element;
    };
    interface HTMLAppFocus2Element extends Components.AppFocus2, HTMLStencilElement {
    }
    var HTMLAppFocus2Element: {
        prototype: HTMLAppFocus2Element;
        new (): HTMLAppFocus2Element;
    };
    interface HTMLAppFocus3Element extends Components.AppFocus3, HTMLStencilElement {
    }
    var HTMLAppFocus3Element: {
        prototype: HTMLAppFocus3Element;
        new (): HTMLAppFocus3Element;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppInputElement extends Components.AppInput, HTMLStencilElement {
    }
    var HTMLAppInputElement: {
        prototype: HTMLAppInputElement;
        new (): HTMLAppInputElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-focus1": HTMLAppFocus1Element;
        "app-focus2": HTMLAppFocus2Element;
        "app-focus3": HTMLAppFocus3Element;
        "app-home": HTMLAppHomeElement;
        "app-input": HTMLAppInputElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppFocus1 {
    }
    interface AppFocus2 {
    }
    interface AppFocus3 {
    }
    interface AppHome {
    }
    interface AppInput {
        "disabled"?: boolean;
        "form"?: Form;
        "tabIndex"?: number;
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-focus1": AppFocus1;
        "app-focus2": AppFocus2;
        "app-focus3": AppFocus3;
        "app-home": AppHome;
        "app-input": AppInput;
        "app-profile": AppProfile;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-focus1": LocalJSX.AppFocus1 & JSXBase.HTMLAttributes<HTMLAppFocus1Element>;
            "app-focus2": LocalJSX.AppFocus2 & JSXBase.HTMLAttributes<HTMLAppFocus2Element>;
            "app-focus3": LocalJSX.AppFocus3 & JSXBase.HTMLAttributes<HTMLAppFocus3Element>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-input": LocalJSX.AppInput & JSXBase.HTMLAttributes<HTMLAppInputElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
